apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      version: "2.4.1"  # spécifiez la version appropriée
  interval: 5m0s
  values:
    host: 10.100.101.137
    username: admin
    password: admin
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    externalDatabase:
      enabled: false
    internalDatabase:
      enabled: true
      name: nextcloud
