apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 4.6.8
      sourceRef:
        kind: HelmRepository
        name: nextcloud-repo
        namespace: flux-system
  interval: 5m0s
  values:
    nextcloud:
      username: admin
      password: admin
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    externalDatabase:
      enabled: false
    internalDatabase:
      enabled: true
      name: nextcloud
