apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud-repo
  namespace: flux-system
spec:
  url: https://nextcloud.github.io/helm/ # URL du dépôt Helm contenant le chart de Nextcloud
